### ISSUE TITLE
#1 깊은복사와 얕은 복사의 차이 

### ISSUE THREAD

**Issue by hannahf97** [JAVA-codingTest/algorithm-study#14]
## 문제번호 
  - bj14502

## 질문

JAVA로 clone() 할때 분명 어떨때엔 깊은 복사라고 들었던것 같은데 또 2차원 배열로 하니까 얕은 복사라고 했는데 헷갈리네요
for문으로 기존의 배열과 새로만든 배열을 넣는 것이랑
2차원 배열에서 clone을 쓰는것이랑 뭐가 다른거죠 ?

**Comment by yn15** [comment]
클론은 1차원 배열시에만 가능하고 2차원배열은 어떻게 복사하셨는지 알수 있을까요?

**Comment by hannahf97** [comment]
2차원 배열 복사는 다음과 같이 했습니다. 
```java 
for(int i=0; i<N; i++){
     for(int j=0; j<M; j++){
       clone[i][j] = maps[i][j]; 
    }
}
```

**Comment by yn15** [comment]
for (int i = 0; i < arr.length; i++) {
		arr[i] = arrcopy[i].clone();
}

2차원 배열 clone은 이런식으로 하시면 됩니다.
